- components/board/create/Input/contentInput.tsx
- components/board/create/Input/input.style.ts
- components/board/create/Input/titleInput.tsx
> [Feat] 01/24 hanjeonghyun 글 등록 페이지 제목/내용 컴포넌트 #44

- app/(user)/recipes/page.tsx
- components/header/header.tsx
- components/recipe/recipeCard/recipeCard.style.ts
- components/recipe/recipeCard/recipeCard.tsx
- components/recipe/recipeCard/recipeCardSlide.style.ts
- components/recipe/recipeCard/recipeCardSlide.tsx
- components/recipe/tag/tag.style.ts
- components/recipe/tag/tag.tsx
- Feat_Tag and Link to details
> [Feat] 01/27 Jyservice781 Feat_Tag #52

- app/(user)/boards/create/page.tsx
- components/board/create/Input/contentInput.tsx
- components/board/create/Input/titleInput.tsx
> [Feat] 01/28 hanjeonghyun 게시글 등록 페이지 구현 #61

- components/board/create/imageBox/imageBox.style.ts
- components/board/create/imageBox/imageBox.tsx
> [Feat] 01/28 hanjeonghyun 등록 페이지 이미지 컴포넌트 구현 #45

- components/recipe/create/recipeCreate.style.ts
- components/recipe/create/recipeCreate.tsx
- components/recipe/create/recipeStepAndImage.style.ts
- components/recipe/create/recipeStepsAndImage.tsx
> [Feat] 01/31 Jyservice781 멀티 이미지 preview #79

- app/(user)/recipes/page.tsx
> [Feat] 01/31 Jyservice781 슬라이드 분리 #82

- app/admin/boards/page.tsx
- app/admin/layout.tsx
- app/admin/page.tsx
- app/admin/quests/page.tsx
- app/admin/recipes/page.tsx
- app/admin/users/page.tsx
- components/footer/adminFooter/adminFooter.style.ts
- components/footer/adminFooter/adminFooter.tsx
- components/header/adminHeader/adminHeader.style.ts
- components/header/adminHeader/adminHeader.tsx
- components/header/header.tsx
- components/index/admin/adminPage.style.ts
- components/index/admin/adminPage.tsx
- components/user/logout/logout.style.ts
- components/user/logout/logout.tsx
> [Feat] 01/31 Jyservice781 어드민 페이지 #86

- app/admin/boards/page.tsx
- app/admin/quests/page.tsx
- app/admin/users/page.tsx
> [Fix] 02/03 Jyservice781 Fix_file #86

- app/(user)/boards/page.tsx
- components/board/overview/overview.style.ts
- components/board/overview/overview.tsx
- components/board/searchBar/searchBar.style.ts
- components/board/searchBar/searchBar.tsx
> 커뮤니티 - 서치바 컴포넌트 분리

- application/recipe/DfRecipeDetailUsecase.ts
- domain/repositories/recipes/RecipeIngredientRepository.ts
- infrastructure/repostiories/recipes/SbRecipeCommentRepository.ts
- infrastructure/repostiories/recipes/SbRecipeIngredientRepository.ts
- Feat-architecture
1. 아키텍처 관련 파일 생성
> [Feat] 02/03 Jyservice781 Feat-architecture #86

- domain/entities/boards/BoardComment.ts
- 커뮤니티 댓글 엔티티 추가
- 엔티티 코멘트 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/03 hanjeonghyun 커뮤니티 댓글 엔티티 추가 #103

- app/api/recipes/route.ts
- application/recipe/DfRecipeListUsecase.ts
- 레시피 어댑터 생성
- 레시피 어댑터 생성 GET 메서드 생성
> [Feat] 02/03 Jyservice781 어댑터 #99

- domain/repositories/boards/BoardCommentRepository.ts
- infrastructure/repostiories/boards/SbBoardCommentRepository.ts
- infrastructure/repostiories/boards/SbBoardImageRepository.ts
- 커뮤니티 부분 레포지토리 코드 추가
- 쿼리에서 테이블 코드 삭제
- 보드 코멘트 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/03 hanjeonghyun 인프라 코드 추가 및 쿼리 수정 #107

- domain/entities/admin/User.ts
- 유저 엔티티 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/03 hanjeonghyun 유저 엔티티 추가 #109

- components/board/optionButton/optionButton.tsx
- 보드 임시 데이터 수정
- 
슈파베이스 토대로 보드 임시 데이터 수정
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/03 hyun9758 보드 태그 수정 #111

- components/board/overview/overview.style.ts
- components/board/searchBar/searchBar.style.ts
#114 
- SearchBar 컴포넌트 스타일 수정
- 기존 호출됐었던 board 페이지의 Overview 스타일 수정
|기능|스크린샷|
|:--:|:--:|
|||
> [Fix] 02/03 hanjeonghyun SearchBar 컴포넌트스타일오류 수정 #114

- components/index/pages/subPage.style.ts
#117
- 메인페이지 스타일 높이를 100vh로 변경
|기능|스크린샷|
|:--:|:--:|
|||
> [Style] 02/03 hanjeonghyun 메인페이지 스타일 변경 #117

- components/index/pages/subPage.style.ts
- components/index/pages/subPage.tsx
#122
- 메인페이지 width 조절
|기능|스크린샷|
|:--:|:--:|
|||
> [Style] 02/03 hanejeonghyun 메인페이지 너비 조절 #122

- application/boards/DfBoardListUsecase.ts
- domain/repositories/boards/BoardImageRepository.ts
보드 이미지를 추가하는 함수를 유스케이스에 추가
보드 이미지 레포지터리와 보드 이미지 유스케이스 파일 수정
후에 유스케이스 함수의 리턴값을 합쳐야 할 필요가 있다면 합치기
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/04 hyun9758 커뮤니티 - Image Usecase #128

- app/api/recipes/[id]/route.ts
- app/api/recipes/route.ts
- application/recipe/dto/RecipeIngredientDto.ts
- application/recipe/dto/RecipeStepDto.ts
- domain/repositories/recipes/RecipeImageRepository.ts
- domain/repositories/recipes/RecipeIngredientRepository.ts
- domain/repositories/recipes/RecipeRepository.ts
- domain/repositories/recipes/RecipeStepRepository.ts
- infrastructure/repositories/recipes/SbRecipeImageRepository.ts
- infrastructure/repositories/recipes/SbRecipeIngredientRepository.ts
- infrastructure/repositories/recipes/SbRecipeRepository.ts
- infrastructure/repositories/recipes/SbRecipeStepRepository.ts
- Feat_POST
- POST 작업 완료
NextRequest 사용 부분 참고하면 좋을 것 같습니다.!
> [Feat] 02/03 Jyservice781 Feat_POST #133

- components/index/admin/adminPage.style.ts
- components/recipe/recipe.style.ts
- Fix_design
Fix_ container padding
> [Fix] 02/04 Jyservice781 Fix_design #135

- app/(user)/boards/page.tsx
- application/board/DfBoardListUsecase.ts
- 하단에 페이지네이션 바 구현
- 데이터가 증가하면 페이지 늘어나는 것 확인
- 페이지네이션 바 구현
|기능|스크린샷|
|:--:|:--:|
|||
> 커뮤니티 - 페이지네이션 

- app/(user)/boards/page.tsx
- components/board/optionButton/optionButton.tsx
- infrastructure/repositories/recipes/SbRecipeTagRepository.ts
- 태그 버튼을 누르면 필터링 기능 수행
- 슈파베이스에서 받아온 데이터 가져오기
- 태그에 따라 필터링하기
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/07 hyun9758 커뮤니티 - 필터링 기능 구현 #152

- components/index/pages/subPage.style.ts
- components/index/pages/subPage.tsx
#124 
- 반응형 코드 추가
- 약한 스크롤로도 다음 섹션으로 넘어가도록 풀스크롤 페이지 구현
- 섹션으로 바로 갈 수 있는 버튼 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/09 hanjeonghyun 풀페이지스크롤 구현 #124

- app/(user)/recipes/[id]/page.tsx
- app/api/recipe-comments/route.ts
- application/recipe-comment/DfRecipeCommentListUsecase.ts
- application/recipe-comment/dto/RecipeCommentCreateDto.ts
- application/recipe-comment/dto/RecipeCommentImageDto.ts
- components/recipe/recipeDetail/recipeReview/cookReview.tsx
- components/recipe/recipeDetail/recipeReview/photoReview.style.ts
- components/recipe/recipeDetail/recipeReview/photoReview.tsx
- domain/repositories/RecipeCommentImageRepository.ts
- infrastructure/repositories/recipes/SbRecipeCommentImageRepository.ts
- infrastructure/repositories/recipes/SbRecipeCommentRepository.ts
- PhotoReview 컴포넌트에서 여러 이미지를 표시하도록 이미지 처리 기능 추가
- CookReview 컴포넌트에서 reviewData를 PhotoReview로 전달하도록 수정
- 이미지 겹침 문제 해결을 위해 스타일 조정 및 유효한 이미지 URL 확인
- PhotoReview에서 이미지 페이지네이션을 위한 네비게이션 버튼 추가
- 유효한 이미지 데이터를 필터링하고 올바르게 표시하도록 개선
> [Fix] 02/10 RomaneeChoiti reviewImgRender #171

- app/(user)/boards/page.tsx
- app/api/boards/route.ts
- components/board/filterBar/filterBar.tsx
- components/board/main/cardPost/cardPostItem.tsx
하트 수를 바탕으로 인기순 버튼을 눌렀을 때 필터링 
- 슈파베이스에 임의로 하트 수 데이터 넣기
-  HTML 코드에서 하트 수, 조회수 수정
- 인기순 바탕으로 필터링 기능 구현
- 
|기능|스크린샷|
|:--:|:--:|
|||
> 커뮤니티 - 인기순 필터링 기능 구현

- app/(user)/boards/create/page.tsx
- app/api/boards/route.ts
- application/board/DfBoardCreateUsecase.ts
- application/board/DfBoardListUsecase.ts
- application/board/dto/BoardCreateDto.ts
- application/board/dto/BoardImageDto.ts
- domain/repositories/BoardImageRepository.ts
- infrastructure/repositories/boards/SbBoardImageRepository.ts
#190 
- 이미지 등록 시 storage -> url로 저장하도록 로직 수정
- BoardCreateDto, BoardImageDto 타입 수정
|기능|스크린샷|
|:--:|:--:|
|||
> [Fix] 02/11 hanjeonghyun 게시글 이미지 등록 개선 #190

- components/user/login/loginBox/loginForm.style.ts
- components/user/login/loginBox/loginForm.tsx
#191
- 단순 유효성 검사 에러 메세지 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/11 hanjeonghyun 유효성 에러 메세지 추가 #191

- app/api/boards/detail/route.ts
- application/board/DfBoardDetailUsecase.ts
- components/board/detail/post/post.style.ts
- components/board/detail/post/post.tsx
- domain/repositories/BoardRepository.ts
- infrastructure/repositories/boards/SbBoardRepository.ts
#199
게시글 삭제 기능 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/12 hanjeonghyun 게시글 삭제 기능 추가 #199

- app/admin/recipes/page.tsx
#201
- 어드민 페이지의 레시피 테이블 추가
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/12 hanjeonghyun 어드민 레시피 테이블 추가 #201

- app/api/recipe-comments/route.ts
- components/board/detail/comment/comment.style.ts
- components/board/detail/comment/comment.tsx
- 댓글 UI 개선
- Delete 구문 추가
- 댓글 삭제 기능 개선 필요
|기능|스크린샷|
|:--:|:--:|
|||
> [Feat] 02/12 hyun9758 댓글 삭제 기능 구현 #189

- application/recipe/DfRecipeListUsecase.ts
- components/recipe/recipeDetail/cookingStep/cookingSteps.tsx
- components/recipe/recipeDetail/recipeReview/cookReview.tsx
- components/recipe/recipeDetail/reviewModal/reviewModal.tsx
- domain/repositories/RecipeIngredientRepository.ts
- hook/useRecipe.ts
- infrastructure/repositories/recipes/SbRecipeIngredientRepository.ts
- store/useRecipeStore.ts
> [Feat] 02/11 Jyservice781 Feat_Store #185

- components/recipe/recipeDetail/recipeReview/cookReview.tsx
- components/recipe/recipeDetail/reviewModal/reviewModal.tsx
승원님 오래기다리셨습니다 이제 작업해도 될 것 같아요!!ㅠㅠ
> pull develop

- components/header/adminHeader/adminHeader.tsx
- components/header/header.tsx
- components/user/login/login.tsx
#215
|기능|스크린샷|
|:--:|:--:|
|||
> [Refactor] 02/13 hanjeonghyun 디테일 이슈 해결 #215

- components/board/main/cardPost/cardPostItem.tsx
- infrastructure/repositories/boards/SbBoardImageRepository.ts
#220 
|기능|스크린샷|
|:--:|:--:|
|||
> [Fix] 02/13 hanjeonghyun 대표 이미지 개선 #220
